### ISSUE TITLE
Configurable private key size

### ISSUE THREAD

**Issue by vincenzodnp** [tnozicka/openshift-acme#120]
**What would you like to be added**:
At the moment the keysize is a hard-coded value of 4096 bytes.
https://github.com/tnozicka/openshift-acme/blob/c1206f8c0849e8ec7b5b1a55e0a2b8aa970c9a97/pkg/controller/route/route.go#L1060-L1068
It might be useful to parameterize it for example by reading an annotation.

**Why is this needed**:
Some CDNs don't support private keys bigger than 2048 bytes

@tnozicka

**Comment by tnozicka** [comment]
annotation with preferred key size sounds doable

**Comment by ferrymanders** [comment]
+1 from us.
We've been using the openshift-acme for about 1.5 years now and we adjusted the previous version to 2048 bit key. 
This is because a 2048 bit key is deemed safe until about 2030 and we've tested with 2048 and 4096 bit keys and the 4096 bit key used about 7~8x more cpu resources on the router pods.

**Comment by tnozicka** [comment]
https://github.com/tnozicka/openshift-acme/pull/124 allows you to have a choice
