### ISSUE TITLE
Renew fix doesn't work on reecnrypt routes

### ISSUE THREAD

**Issue by andrewklau** [tnozicka/openshift-acme#16]
It seems my renew fix from here does not work with reencrypt routes https://github.com/tnozicka/openshift-acme/pull/13

It needs to match the `route.Spec.Tls.Termination = "reencrypt"` for the renew to work.

**Comment by andrewklau** [comment]
It seems we may need to create the temporary route to be based on whatever TLS termination the main route is using.

For re-encrypt we can include a dummy destination certificate and set the `InsecureEdgeTerminationPolicy` (redirect shares the same policy name) to `Allow`, so the challenge will be accepted. A dummy destination certificate will be required for it to be accepted by the router. 

I've tested this logic and it appears to work. Unfortunately I don't think I will have time any time soon to look into a patch for this.

**Comment by andrewklau** [comment]
@tnozicka I opened an issue here https://github.com/openshift/origin/issues/14950

I'm not sure how to fix this, I think even when I changed the route to "reencrypt" and added a dummy DestinationCACertificate the renewal process still failed.

**Comment by jam13** [comment]
I have got this working on our dev cluster (3.6.0), but not in the case where the reencrypt route is also a redirect.

- edge + none = ok
- edge + allow = ok
- edge + redirect = ok
- reencrypt + none = ok
- reencrypt + allow = ok
- reencrypt + redirect = fail

Redirect routes seem to fail in all cases on ibotty/openshift-letsencrypt (at least in the setup that I've got), which is why I've been testing this code. I think the reason for this might be that it always creates routes in the same namespace as the letsencrypt pod which requires you to run the router with the `ROUTER_DISABLE_NAMESPACE_OWNERSHIP_CHECK` flag (it's not really designed for serving multiple namespaces). Maybe the order in which rules are being generated in the router template is having an effect?

**Comment by jam13** [comment]
https://github.com/openshift/origin/blob/release-3.6/images/router/haproxy/conf/haproxy-config.template#L191-L203

I'm not an haproxy expert, but afaics the current rules mean that redirect rules match before any "Allow" rules, irrespective of how specific the regexes are. Reversing the order would just mean that redirects in path routes wouldn't work.

**Comment by jam13** [comment]
I've submitted a pull request to fix issue you raised above. It can be tested by overriding the haproxy template (https://docs.openshift.org/latest/install_config/router/customized_haproxy_router.html#using-configmap-replace-template)

Here's a patched template file for router v1.5.1:
[haproxy-config.template.txt](https://github.com/tnozicka/openshift-acme/files/1232754/haproxy-config.template.txt)

**Comment by jperville** [comment]
Here is my patched template file for router v3.6.1: [haproxy-config.template.txt](https://github.com/tnozicka/openshift-acme/files/1521199/haproxy-config.template.txt). Looking forward to seeing the PR merged.

**Comment by tnozicka** [comment]
fixed (hacked) in https://github.com/tnozicka/openshift-acme/pull/48
