### ISSUE TITLE
Deployment Updates

### ISSUE THREAD

**Issue by tobru** [tnozicka/openshift-acme#25]
As we're slowly moving APPUiO to the openshift-acme controller we've built an automated deployment process. It's based on Ansible and can be found here: https://github.com/appuio/ansible-role-openshift-acme. We're also currently building our own Docker image as it seems that the used S2I builder is not maintained: https://github.com/appuio/openshift-acme-docker and https://hub.docker.com/r/appuio/openshift-acme/.

If you want you can link it in the README and probably remove the files under `deploy/`. The linked Ansible role contains a proper OpenShift template: https://github.com/appuio/ansible-role-openshift-acme/blob/master/files/acme-controller-template.yml. This can also be used standalone without the Ansible role.

**Comment by LorbusChris** [comment]
The role doesn't work on OpenShift Online out of the box as the user there cannot create cluster roles.
I hope for some clarification on how to deploy it on Online in the thread linked above. Would you consider supporting an option for deployment without the cluster role within your role?

**Comment by tobru** [comment]
Good point. We maybe could split it up into two templates: One for the project-specific stuff which doesn't need admin rights and one for cluster-admins. I will try to find a solution as I find time. And on a sidenote: https://www.appuio.ch supports it out-of-the-box =)

**Comment by LorbusChris** [comment]
@tnozicka @tobru fyi I'll try to get a template into the origin repo as an example that can be deployed on `oc cluster`.

There's currently two approaches to building the controller docker image: The s2i build by @tnozicka and https://github.com/appuio/openshift-acme-docker. They're both on Docker hub.

@dustymabe Do you think its possible to also get the controller Docker image built in the CentOS or Fedora buildsystem(s)? I think makes sense for this container because it'll be depended on in a template in the origin repo, and will therefore require security auditing.

**Comment by tobru** [comment]
I'd be happy to deprecate our APPUiO Docker image in favour of an official image 👍

**Comment by tnozicka** [comment]
The build is currently happening in Travis CI on every merge to master. This is likely to move OpenShift CI when the switch comes.
