### ISSUE TITLE
cannot unmarshal number into Go value of type string

### ISSUE THREAD

**Issue by sabre1041** [tnozicka/openshift-acme#29]
Seeing this issue with the most recent image. Was not seeing this error previously with the same configuration in the same cluster

```
2017-09-06T01:30:17.028605154Z   INFO Starting controller
  | 2017-09-06T01:30:17.028756809Z   INFO ACME server url is 'https://acme-v01.api.letsencrypt.org/directory'
  | ERROR: logging before flag.Parse: W0906 01:30:17.028786       1 client_config.go:481] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
  | 2017-09-06T01:30:17.032524381Z   INFO AcmeController bootstraping DB
  | 2017-09-06T01:30:17.032552688Z  TRACE AcmeController bootstraping DB finished duration=40.403775ms start=2017-09-06T01:30:17.032552956Z end=2017-09-06T01:30:17.072956731Z
  | 2017-09-06T01:30:17.073004363Z   INFO AcmeController initializing
  | 2017-09-06T01:30:17.073057872Z   INFO AcmeController started
  | 2017-09-06T01:30:17.073306846Z   INFO Http-01: server listening on http://[::]:5000/
  | 2017-09-06T01:30:17.076501091Z   INFO RouteController initializing
  | 2017-09-06T01:30:17.076537988Z   INFO RouteController started
  | 2017-09-06T01:30:17.076562431Z   INFO RouteController: watching namespace ''
  | 2017-09-06T01:30:17.079674842Z  ERROR route.go:115 json: cannot unmarshal number into Go value of type string
  | 2017-09-06T01:30:17.079733483Z  ERROR route.go:192 RouteController: doWatchIteration failed: RouteController: failed to unmarshal Route: 'json: cannot unmarshal number into Go value of type string'
  | 2017-09-06T01:30:27.082780726Z   WARN route.go:98 RouteController: resetting resourceVersion: caused by 'ERROR' (unversioned.Status{TypeMeta:unversioned.TypeMeta{Kind:"Status", APIVersion:"v1"}, ListMeta:unversioned.ListMeta{SelfLink:"", ResourceVersion:""}, Status:"Failure", Message:"too old resource version: 2366 (10997)", Reason:"Gone", Details:(*unversioned.StatusDetails)(nil), Code:410})
  | 2017-09-06T01:30:27.082814043Z  ERROR route.go:192 RouteController: doWatchIteration failed: RouteController ResultChannel closed
 ```

Same symptoms in OpenShift Container Platform 3.5 and 3.6

**Comment by tnozicka** [comment]
@sabre1041 do you have a Route which has port of type int instead of string?
I don't think this is connected to newer image as this was problem from the beginning.
https://github.com/tnozicka/openshift-acme/blob/master/pkg/openshift/api/route.go#L17

I am working on plumbing in the clientsets from OpenShift which should fix all of those issues.

**Comment by sabre1041** [comment]
@tnozicka you are right. Had a few routes that defined a `targetPort` with Integer type. Modified them to be defined as integers and the errors went away.

Glad to hear that they should be removed with the future work you are developing

How do you want to handle this issue?

**Comment by tnozicka** [comment]
Let's keep it open so people know there is a workaround and I will close it when that's properly fixed.

(I will close the older dupe as this one is more descriptive.)

**Comment by mhutter** [comment]
What's the workaround here? I just hit the same Issue :-/

```
$ oc get route --all-namespaces -o json | jq -r '.items[] | select(.metadata.annotations | has("kubernetes.io/tls-acme")) | .spec.port.targetPort'
8080-tcp
null
waf
pspdfkit
https-endpoint
```

**Comment by jfchevrette** [comment]
@tnozicka I just hit this issue on a multi-tenant cluster I manage. I've fixed the services/routes on the cluster but an end-user is still able to create a service/route combo with an integer targetPort which could cause openshift-acme to stop working.

Would it be possible for openshift-acme to skip over the routes it can't unmarshal and keep going instead of crashing?

**Comment by tnozicka** [comment]
probably just replacing this `return` with `continue` https://github.com/tnozicka/openshift-acme/blob/4c651088dbbc6658f2bfef5d2b340379c8989984/pkg/openshift/controllers/route/route.go#L116

@jfchevrette I am in process of re-writing the whole controller to shared informers, workqueue and openshift client so the fix for all the important issues including this one is on the way

**Comment by jfchevrette** [comment]
@tnozicka how is the rewrite coming along? I see the move to shared informers in the `rewrite` branch. Is it ready for consumption/testing yet?

**Comment by tnozicka** [comment]
@jfchevrette rewrite (https://github.com/tnozicka/openshift-acme/pull/48) is almost done. Don't be scared on the red test - I just need to do few fixes in CI and test framework, the tests are actually passing. (If you check the tests from close you'll see that the cluster wide part is green even there.) The secret synchronization isn't done yet, but that's like few hours of work. Unless you use the generated secrets I think you should be good to go - it should be better than what's in master now. Definitely worth testing it and providing feedback.

I still need to respond to the feedback I got [there](https://github.com/tnozicka/openshift-acme/issues/47), low on time due to fixing bugs in OpenShift.

(Note that the publishing is not happening because of broken CI for now, so you need to run `make image` locally to have latest)

**Comment by tnozicka** [comment]
fixed in https://github.com/tnozicka/openshift-acme/pull/48
