### ISSUE TITLE
refactor assistance

### ISSUE THREAD

**Issue by twhiston** [tnozicka/openshift-acme#47]
Hi,
Firstly thanks for the great project its really cool to see acme in Openshift! Secondly I see you are in the middle of a rewrite of the code, some of the features (retry limiting, global account etc.....) are things that would be really useful to us, so I'd like to offer my help in the refactoring process.-However I don't see a clear outline of how to help with the refactoring on here to just jump in, so 1) are you open to some help? 2) if so what can I help with? :)

**Comment by tnozicka** [comment]
Hi @twhiston, thanks for the offer to help, always appreciated :)

I think I am closing in and I want to merge the rewrite soon in a minimal form and build features on top of it. Global account is already present and part of the new design. Rate limiting is there from the queue and with pausing the route. Although if you would intentionally try to DOS it, it wouldn't be enough. Proper rate limiting will be one of the first features when this gets merged but I already have the design in my head based on kube cache.ttlstore (similar to kube expectations). 

I am not sure if any development time would help before that gets merged and work can be started on features.

What would help most at this point is for you to try it and test if it works for you. Also trying the upgrade scenario would be very helpful. And when I make the PR with rewrite, at least a brief code review would help as well.

**Comment by twhiston** [comment]
Hi @tnozicka, very happy to help with those things, and contributing features once the rewrite is in main.....
If its ready for some testing right now i would be happy to do that before the start of next week, and always happy to code review, just let me know when you need it.

**Comment by tobru** [comment]
Same here, we're happy to help, test, contribute. Whatever needed to make it awesome!

**Comment by tnozicka** [comment]
thanks guys! I have published what I have right now in https://github.com/tnozicka/openshift-acme/pull/48. I need to cleanup the code before code reviews but tests are passing and I would appreciate if you could try it out early and provide feedback.

**Comment by schemen** [comment]
Hi!

I've tested the clusterwide configuration so far and after some kicking it started working nicely.

- "oc adm policy add-cluster-role-to-user cluster-admin -z openshift-acme" is required, the cluster role does not seem to work. The problem seems to be that he is not allowed to create routes to acme-controller pod

- https://github.com/tnozicka/openshift-acme/issues/42 seems to be resolved. I have not been able to replicate it now
- Because it is pre-alpha I suppose the output is verbose?
- Before getting it to work, I seemed to struggle with some secrets. I deleted them, recreated pods and at some point things started working

    * `ERROR dbcertentry.go:79 [domain: <DOMAIN>, error: 403 urn:acme:error:unauthorized: No registration exists matching provided key]`

- Usual operations work so far

Hope this helps as an initial feedback!

**Comment by tobru** [comment]
I gave the rewrite a test (using the image `docker.io/tnozicka/openshift-acme:v0.8.0-pre-alpha`) and as far as I can tell it works as expected.

From my point of view, the migration path from the previous version looks like this:

1. CLEANUP: Delete old secrets: `acme-account` and `acme.$NAME` from project if using a global acme controller
1. WORKAROUND: Remove all HTTPS configuration from route: `spec.tls`
1. Wait for controller to request a new certficate and reconfigure the route

When not doing point 2 from above, I get for routes which already have expired certificates:

```
E0114 16:49:16.869135      14 exposer.go:267] Failed to GET "http://example.com/.well-known/acme-challenge/gxiCyzkbobyP2HeLIwb0I_psuqSizb9zufJ5ssQy0js": Get https://example.com/.well-known/acme-challenge/gxiCyzkbobyP2HeLIwb0I_psuqSizb9zufJ5ssQy0js: x509: certificate has expired or is not yet valid
```

The only thing I'm currently missing is the feature already mentioned in README: "Creating associated Secrets for Routes containing the certificate".

**Comment by twhiston** [comment]
I just gave the rewrite a try also using the pre-alpha image and ran in to some issues

Like @tobru I performed the cleanup and workaround steps but then ran in to a different issue
```
E0116 15:17:30.975550       1 route.go:526] failed to accept ACME authorization: failed to create exposing Endpoints xxxx/kb-ssl-acme-forwarder: endpoints "kb-ssl-acme-forwarder" is forbidden: endpoint address xx.xxx.x.xxx is not allowed
--
  | I0116 15:17:30.975570       1 route.go:527] Dropping Route "xxxx/kb-ssl" out of the queue: failed to accept ACME authorization: failed to create exposing Endpoints xxxx/kb-ssl-acme-forwarder: endpoints "kb-ssl-acme-forwarder" is forbidden: endpoint address xxx.xxx.x.xxx is not allowed
```
I also saw a similar issue that referenced this https://github.com/tnozicka/openshift-acme/issues/28#issuecomment-327329198 and the fix suggestion, but when I checked the service the cluster IP was already set to none and cannot be changed due to immutability (and to be clear this is a self hosted openshift and not the redhat operated PaaS that I am testing in)

**Comment by tnozicka** [comment]
@schemen @tobru @twhiston thaks everyone for the feedback!

I am low on time now, but just wanted to let you know I read it and I plan to address your comments fully when I get the time. But at least quickly for now:

@schemen 
>"oc adm policy add-cluster-role-to-user cluster-admin -z openshift-acme" is required, the cluster role does not seem to work. The problem seems to be that he is not allowed to create routes to acme-controller pod

What openshift version do you use? Have you created the new role from https://github.com/tnozicka/openshift-acme/blob/rewrite/deploy/letsencrypt-staging/cluster-wide/clusterrole.yaml#L14
We test the full setup in CI for v3.6.1 and it works. (I'll try to add 3.7.1 now that's out there, 3.7.0 was broken on travis.)

> Because it is pre-alpha I suppose the output is verbose?

You can specify whatever logging level you want (0-9) here https://github.com/tnozicka/openshift-acme/blob/rewrite/deploy/letsencrypt-staging/cluster-wide/deployment.yaml#L33 .  I chose higher one to be the default so people deploying it for the first time know what's going on and the more advanced user can always adjust it (lower it).

> Before getting it to work, I seemed to struggle with some secrets. I deleted them, recreated pods and at some point things started working
ERROR dbcertentry.go:79 [domain: <DOMAIN>, error: 403 urn:acme:error:unauthorized: No registration exists matching provided key]

That's an error from the old controller when you mix staging key with live or vice versa

> Usual operations work so far

Great!


@tobru 
> When not doing point 2 from above, I get for routes which already have expired certificates:

Fixed it already - the controller was checking whether the route is exposed and it didn't disable certificate check (there was the old cert for a while).

> The only thing I'm currently missing is the feature already mentioned in README: "Creating associated Secrets for Routes containing the certificate".

great; I'll add it once I fix the CI; (easy feature)

@twhiston 
> endpoint address xx.xxx.x.xxx is not allowed

Hmm, that's weird and should happen with this new version. The old version used to set IP from service IP range to endpoints (which should be from pod IP range) - that's why it didn't work in Online. This new version sets acme controller's pod's IP into the endpoints so it should work I think. Interested to see the details on this. I didn't have a chance yet to try this on Online.

**Comment by tnozicka** [comment]
So I tried Online and you it denies you setting even pod's IP into endpoint without having endpoints/restricted permission, which regular user can't set. 

There is always the possibility of running a pod for a while to do the redirection without special permissions but I'm trying to avoid it if possible.

**Comment by LorbusChris** [comment]
I'm guessing it's because they don't want to allow any traffic into the cluster that is not load-balanced.

Definitely am curious how things will look with envoy/istio...  

btw I made an APB for deploying OpenShift-ACME:
https://github.com/LorbusChris/openshift-acme-installer
(I called it installer because it is a non-standard APB as it needs cluster-admin priveleges to deploy; it can still be used to manage the entire lifecycle (incl. updates/deprovisioning))

**Comment by tnozicka** [comment]
I found out it's because it would allow you to avoid network isolation by the network plugin. Testing the workaround now.

@LorbusChris fyi deploying should be really straightforward now with
https://github.com/tnozicka/openshift-acme/blame/rewrite/deploy/letsencrypt-live/cluster-wide/README.md#L15-L16

no need for APB (if there is ever need for it, but I am being biased here)
in deprovisioning you usually delete the namespace or do just something like `oc delete all,role -l app=openshift-acme`

(I don't think istio will be easy in multitenant environment.)

**Comment by LorbusChris** [comment]
@tnozicka ah ok interesting.
One of the main reasons I think APBs are cool is that you can create update roles. Simplifies things a lot for non-technical ppl.

Just one more Q: Isn't it possible to put the policy in the template as well?

**Comment by tnozicka** [comment]
> One of the main reasons I think APBs are cool is that you can create update roles. Simplifies things a lot for non-technical ppl.

Not considering other factors, Just the prerequisity of installing ansible for those people is seems like inappropriate. Any user already has `oc create`, issuing that command seems simple enough to me. But I guess we are drifting away.

if it would be a template you could do that likely by adding this yaml output:
`oc policy add-role-to-user edit -z openshift-acme -o yaml`

**Comment by tnozicka** [comment]
We are at the next round of testing if anyone feels like it. Issues should be addressed, CI tests are green.

https://github.com/tnozicka/openshift-acme/pull/48#issuecomment-363541265

Whoever will try the single-namespace (unrestricted) option know that you need to pickup this https://github.com/openshift/origin/pull/18312.
(See the CI hack https://github.com/tnozicka/openshift-acme/blob/28b542639d913d6a00c1ef5aa6cd966c575be1ee/hack/run-extended-test-on-all-versions.sh#L44-L46)

**Comment by tobru** [comment]
I gave the latest image from Docker hub a try: At first sight it looks good and it is able to request new certificates. However: It seems like the forwarder routes are not removed after the certificate has been issued. Is this by intention?

**Comment by samjaninf** [comment]
I tested the new build I'm running into a strange issue. It might just be the way I have my openshift instance configured but it seems to be some sort of issue with the internal networking:

````
I0210 19:34:36.412972       1 route.go:385] Started syncing Route "rcomm-test/react" (2018-02-10 19:34:36.412919664 +0000 UTC m=+231208.514162975)
I0210 19:34:36.520126       1 route.go:483] Route "rcomm-test/react": authorization state is "pending"
I0210 19:34:36.520172       1 client.go:83] Found 2 possible combinations for authorization
I0210 19:34:36.520180       1 client.go:90] Found 1 valid combinations for authorization
I0210 19:34:36.520192       1 exposer.go:118] route namespace: "rcomm-test"
I0210 19:34:36.520198       1 exposer.go:119] self namespace: "letsencrypt"
I0210 19:34:36.520203       1 exposer.go:120] self selector: map[]
I0210 19:34:36.594461       1 request.go:462] Throttling request took 385.871819ms, request: PUT:https://172.30.0.1:443/api/v1/namespaces/**********/services/test-acme-forwarder 
I0210 19:34:36.794502       1 request.go:462] Throttling request took 274.196156ms, request: POST:https://172.30.0.1:443/api/v1/namespaces/rcomm-test/services 
W0210 19:34:36.813201       1 exposer.go:144] Forwarding Service / already exists, forcing rewrite
I0210 19:34:36.994538       1 request.go:462] Throttling request took 351.433274ms, request: POST:https://172.30.0.1:443/api/v1/namespaces/**********/endpoints 
I0210 19:34:36.998708       1 route.go:387] Finished syncing Route "**********/test" (1.787469579s)
E0210 19:34:36.998750       1 route.go:719] failed to accept ACME authorization: failed to create exposing Endpoints **********/test-acme-forwarder: endpoints "test-acme-forwarder" is forbidden: endpoint address 10.129.2.62 is not allowed
I0210 19:34:36.998760       1 route.go:720] Dropping Route "**********/test" out of the queue: failed to accept ACME authorization: failed to create exposing Endpoints **********/test-acme-forwarder: endpoints "test-acme-forwarder" is forbidden: endpoint address 10.129.2.62 is not allowed
````

**Comment by srueg** [comment]
Hi there. First also a thank you for the great project!
I had issues with the controller creating acme-forwarder routes with `insecureEdgeTerminationPolicy: None` but the controller tried the http url:
```
I0213 20:32:12.958195       1 exposer.go:336] Failed to GET "http://xxx.xxx.xx/.well-known/acme-challenge/mn0rCPgRXv0FrZaZCrxF8iqqA789E9Q7SBIya9fIqTo":  503 Service Unavailable: <html>
```
After manually changing the policy to `Allow`, the validation was successful. Also as mentioned by @tobru, the acme-forwarder routes are not cleaned up.
I skipped the [clean up steps](https://github.com/tnozicka/openshift-acme/issues/47#issuecomment-357525703) and only deleted the acme account in the controller namespace.
Happy to answer questions or do more testing if necessary.

**Comment by tnozicka** [comment]
Thank you all for trying out this version!

> It seems like the forwarder routes are not removed after the certificate has been issued. Is this by intention?

@tobru Deleting them just wasn't implemented in this PR (it was implemented, just isn't called). It's not a trivial change as I have split up the phases to avoid controller thread to wait while doing the verification so I have to add some context on the route. As this would affect the user experience I am holding this PR till that's done.
The plan is to delete them only on successful runs so you can debug it otherwise. The have OwnerRefs to the main Route they were created for so when deleting the Route they will disappear.

@samjaninf I somehow manage to delete `endpoints/restricted` from the clusterroles - likely because I though it work without it in our CI, but it is needed. (It just doesn't appear in environments that share IP ranges for pods and endpoints and services.) Fixed now.

@srueg As there is no way to detect when the the Route is exposed (only when admitted, but that's before that) few of those failed GETs are a way how we detect it's exposed. That's why it's only Info level. Was it failing permanently for you? Followed by any errors?

**Comment by srueg** [comment]
I tested again and the problem only occurs if a route with `insecureEdgeTerminationPolicy: None` is annotated. The forwarder-route which is then created also has `insecureEdgeTerminationPolicy: None` which then leads to
```
I0214 09:48:39.892646       1 exposer.go:336] Failed to GET "http://test2.xxx.xx.well-known/acme-challenge/oP6rdGuf-sHLQkdwlOv_HaikcKokgx6edSigYNvSziw":  503 Service Unavailable: <html>
```

**Comment by tnozicka** [comment]
@srueg I know why that is; we have a hack to inherit `insecureEdgeTerminationPolicy` to the exposing Route because of [broken path based routing with mixed tls](https://github.com/openshift/origin/issues/14950). But we shouldn't inherit `None` as that can't work. Should be easy fix.

**Comment by tnozicka** [comment]
@srueg `insecureEdgeTerminationPolicy` should be fixed when the tests finish and publish the new image

**Comment by srueg** [comment]
Yes, works as expected 👍  thanks!
