### ISSUE TITLE
challenge-service get created with invalid name when route name contains .

### ISSUE THREAD

**Issue by ibotty** [tnozicka/openshift-acme#50]
Hi,

I just updated from an old version and noticed, that routes with . in their name are not supported anymore. Is that expected?

```
Error syncing Route my_namespace/a.route.com: failed to accept ACME authorization: failed to create exposing Service /a.route.com-acme-r75ks: Service "a.route.com-acme-r75ks" is invalid: metadata.name: Invalid value: "a.route.com-acme-r75ks": a DNS-1035 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
```

**Comment by tnozicka** [comment]
It's not really intentional, just an edge case. The reason is that the new version creates all temporary objects with a prefix based on Route's name for clarity. The issue I didn't know about before is that Route's name has special validation allowing dnsSubdomain as it's name whereas regular Kubernetes objects use dnsLabel.
