### ISSUE TITLE
Prometheus Endpoint

### ISSUE THREAD

**Issue by twhiston** [tnozicka/openshift-acme#53]
Hi, would you have any interest in a prometheus endpoint being added to openshift-acme app where we can count the number of fails for getting certs (rate limits etc....), which would allow for better monitoring?
I saw that basically you just parse the errors in one place `pkg/acme/client/client.go` `func GetAuthorizationErrors` so it seems like we could target something around that function, maybe a general error counter and then specific switches for the type of error that increments individual counters. 
If you have a better idea of where to implement it or you don't want this please shout, otherwise i will get started on it.

**Comment by tnozicka** [comment]
Hi @twhiston, I am in support of prometheus endpoint.

I'd need to look into details on how we want to implement this but I suspect we should scrape it from the managed objects for persistency as the controller could have just restarted. We likely don't store all the info there today, but that can be easily fixed. No real performance hit for listing them all as we keep those in caches.

link to where it is in openshift https://github.com/openshift/origin/blob/29bcdcbfedb2d4b3225483f7b056b3f7cdc7d71a/pkg/apps/metrics/prometheus/metrics.go#L80

**Comment by twhiston** [comment]
ok, thanks for the feedback, i'll start to dig in this a bit more today and see if i can start prototyping something that we can discuss

**Comment by twhiston** [comment]
I was just taking a look deeper in to this and it seems like in the route handle function where you do the status switch would be an easy place to implement this rather than on the objects themselves as this already has all the logic needed other than specific prometheus part.

Please correct me if my thinking is wrong here but if we do it on the object we need to either think about if the status changed from the last time that we scraped it, which means also storing the previous status, or just having a count of 'x objects have error state y', which can go up and down depending on the current status of managed routes, which seems wrong. I think maybe we don't really care about that total, we care about the state change (error code) as it happens and calculating the rate (ie this route just failed for reason 'x' increase counter for 'x', from this we use the rate function in prometheus so that we can set up alerts). We dont actually care if the total gets reset if the controller restarts or is redeployed etc.... because it doesn't really matter. IMO we should have a time series with the error types as a label and just count based on these.

**Comment by tnozicka** [comment]
>  we need to either think about if the status changed from the last time that we scraped it

My thinking is that the status will be synced to the Route itself so you can just read it from annotation. Like we will sync number of failed attempts per Route, the fact that it has been rate limited (by our internal acme limits) and when is the next allowed retry and other info directly to annotations. Should be easy to read it from there in another method given we have the cache for free.

> We dont actually care if the total gets reset if the controller restarts or is redeployed etc.... because it doesn't really matter.

I guess with scraping the actual objects you would avoid spikes on restart in the prometheus graph that would be inaccurate for a while. And the corner cases where controller panics and that metric shows you e.g. 1 failed route (on which it panics) instead of 300 that are actually in failed state.

e.g. the number of failed routes seems like a state of the objects more than a particular run of a controller. (Some won't even fail after the restart if they would wait e.g. for rate limiting.)

> from this we use the rate function in prometheus so that we can set up alerts
I guess for alerts that would be enough, but I'd like to have also nice and accurate graphs in kibana. (Like I want to see the total number of failed Routes through out the time and compare that to other graphs.)

Also that part which is now specific to Routes will be abstracted to allow sharing part of the sync loop for Ingresses and Secrets. So if possible I would prefer avoiding coupling that to prometheus logic if possible.

I was wondering if you could come up with some list of basic metrics we want to collect and we can discuss the best way to implement it based on that.

On a side note shipping a pre-configured openshift-acme dashboard for kibana seems really cool. (Seeing the failures, how old certificates Route have, which failed to renew, which are past the standard renewal time [2/3], which certificates are already expired [managed/unmanaged], ...)

**Comment by hypery2k** [comment]
any progress on this feature so far?

**Comment by tnozicka** [comment]
Sorry, I lost track of this.

> amount of errors with type as a label

+1

> amount of managed certificates (with the state as a label)

+1

> amount of paused routes

Pausing will likely be droped when we have rate limits but I am fine exposing it till then.

> application exceptions

If you mean tracking the counts when openshift-acme panics (restarts) I don't think this is the place. You should be checking the openshift-acme pod restart count.

> We discussed scraping the objects rather than reporting them at the time that the request is made, and
 I think now that you have the pause stuff in place this would be ok for us (our main problem pre-latest version was that if the request failed you had a very short time to do anything before you get rate limited and obviously this is really hard to deal with when you have customers in your cluster using the service)

As Prometheus works in pull model I don't really see the difference here.

> I also really like the idea of a Kibana, or Graphana, dashboard being shipped with this project, as it creates a lot of value up front, and would be super useful for our operations guys.

I guess we use mostly Graphana in OpenShift, so let's ship Graphana dashboard ;)

**Comment by hypery2k** [comment]
will be see a graphana dashboard or promotheus metrics in the near future?

**Comment by hypery2k** [comment]
any news on that?

**Comment by LorbusChris** [comment]
activity!
